import {
  Plus, ArrowLeft, ClipboardList, Paperclip, Megaphone, MessageCircle, Check, CheckCircle2,
  UploadCloud, Trash2, FileText, Pencil, Calendar, ChevronDown, Compass, Flag, Folder, Users,
  HelpCircle, Smartphone, Globe, Flame, MapPin, Lock, LogOut, Mail, Mic, MoreVertical, Bell,
  ExternalLink, Banknote, PlayCircle, Loader2, FileQuestion, PiggyBank, Clock, GraduationCap,
  Search, Settings, Star, Table, ThumbsUp, Timer, Languages, Upload, Video, Briefcase, TrendingUp,
  BookOpen, Trophy, BarChart3, FileBarChart, BadgeCheck, Brain, Medal, Zap, HeartHandshake,
  MessagesSquare, Download, LayoutDashboard, User, SlidersHorizontal, Accessibility, Palette,
  Shield, UserCog, Repeat, Eye, AlertTriangle, CloudOff, Film, Headphones, VideoOff, Frown,
  PartyPopper, Circle, Sparkles, Moon, PersonStanding, IdCard, Building2,
  Wifi, Play, Activity, Menu, DownloadCloud,
  Library, Box, CheckCheck, MailOpen, MoreHorizontal, ArrowRight, CalendarClock, UserCheck, Monitor,
  ChevronsUpDown, Target, ClipboardX, FolderArchive,
  Award, Headset, ChevronRight, ClipboardCheck, Route, FlaskConical, Hourglass, X, ListChecks, StickyNote,
  RefreshCw, Database, ArrowDownUp, File, RefreshCwOff, PieChart, Lightbulb, LayoutGrid, PlusCircle, Tag, ArrowUp, ArrowDown, Info,
  ScanSearch, History, Heart, Rocket, Swords, UserPlus, Handshake, Camera,
  FolderOpen, ShieldCheck, Volume2, Captions, Maximize, Pause, LayoutGrid as AppsIcon,
  EyeOff, Image as ImageIcon, GripVertical, ListFilter, ChevronLeft, Quote,
  FilterX, Copy, TrendingDown, FilePlus2, Send, Save, Bug,
  type LucideIcon,
} from "lucide-react";
import { cn } from "../lib/utils";

const MAP: Record<string, LucideIcon> = {
  add: Plus,
  arrow_back: ArrowLeft,
  assignment: ClipboardList,
  assignment_turned_in: CheckCircle2,
  attach_file: Paperclip,
  campaign: Megaphone,
  chat_bubble: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  cloud_upload: UploadCloud,
  cloud_off: CloudOff,
  delete: Trash2,
  description: FileText,
  edit: Pencil,
  event: Calendar,
  expand_more: ChevronDown,
  explore: Compass,
  explore_off: Compass,
  flag: Flag,
  folder: Folder,
  group: Users,
  groups: Users,
  help: HelpCircle,
  install_mobile: Smartphone,
  language: Globe,
  local_fire_department: Flame,
  location_on: MapPin,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  mic: Mic,
  more_vert: MoreVertical,
  notifications: Bell,
  open_in_new: ExternalLink,
  payments: Banknote,
  picture_as_pdf: FileText,
  play_circle: PlayCircle,
  play_lesson: PlayCircle,
  progress_activity: Loader2,
  quiz: FileQuestion,
  savings: PiggyBank,
  schedule: Clock,
  school: GraduationCap,
  search: Search,
  settings: Settings,
  star: Star,
  stars: Sparkles,
  table_view: Table,
  thumb_up: ThumbsUp,
  timer: Timer,
  translate: Languages,
  travel_explore: Globe,
  upload_file: Upload,
  videocam: Video,
  videocam_off: VideoOff,
  work: Briefcase,
  trending_up: TrendingUp,
  menu_book: BookOpen,
  leaderboard: Trophy,
  analytics: BarChart3,
  summarize: FileBarChart,
  verified: BadgeCheck,
  psychology: Brain,
  military_tech: Medal,
  whatshot: Flame,
  bolt: Zap,
  volunteer_activism: HeartHandshake,
  emoji_events: Trophy,
  forum: MessagesSquare,
  download: Download,
  dashboard: LayoutDashboard,
  person: User,
  tune: SlidersHorizontal,
  accessibility: Accessibility,
  palette: Palette,
  shield: Shield,
  manage_accounts: UserCog,
  repeat: Repeat,
  visibility: Eye,
  warning: AlertTriangle,
  movie: Film,
  headphones: Headphones,
  sentiment_dissatisfied: Frown,
  celebration: PartyPopper,
  radio_button_unchecked: Circle,
  circle: Circle,
  insights: Sparkles,
  dark_mode: Moon,
  directions_run: PersonStanding,
  badge: IdCard,
  domain: Building2,
  install: Smartphone,
  wifi: Wifi,
  cloud_done: CheckCircle2,
  play_arrow: Play,
  offline_pin: DownloadCloud,
  monitoring: Activity,
  menu: Menu,
  local_library: Library,
  work_outline: Briefcase,
  view_in_ar: Box,
  done_all: CheckCheck,
  mark_email_unread: MailOpen,
  more_horiz: MoreHorizontal,
  arrow_forward: ArrowRight,
  event_upcoming: CalendarClock,
  how_to_reg: UserCheck,
  settings_system_daydream: Monitor,
  unfold_more: ChevronsUpDown,
  group_work: Users,
  target: Target,
  assignment_late: ClipboardX,
  folder_zip: FolderArchive,
  workspace_premium: Award,
  support_agent: Headset,
  chevron_right: ChevronRight,
  public: Globe,
  business: Building2,
  fact_check: ClipboardCheck,
  alt_route: Route,
  sports_score: Flag,
  science: FlaskConical,
  calendar_clock: CalendarClock,
  pending_actions: Hourglass,
  signal_cellular_alt: BarChart3,
  close: X,
  checklist: ListChecks,
  notes: StickyNote,
  grading: ClipboardCheck,
  hourglass_empty: Hourglass,
  cloud_download: DownloadCloud,
  sync: RefreshCw,
  storage: Database,
  sort: ArrowDownUp,
  insert_drive_file: File,
  hd: Film,
  sync_problem: RefreshCwOff,
  pie_chart: PieChart,
  lightbulb: Lightbulb,
  grid_view: LayoutGrid,
  library_books: Library,
  work_history: Briefcase,
  add_circle: PlusCircle,
  book: BookOpen,
  category: Tag,
  pending: Clock,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  info: Info,
  search_insights: ScanSearch,
  keyboard_arrow_down: ChevronDown,
  new_releases: Sparkles,
  auto_awesome: Sparkles,
  task_alt: CheckCircle2,
  history: History,
  favorite: Heart,
  rocket_launch: Rocket,
  edit_document: FileText,
  autorenew: RefreshCw,
  swords: Swords,
  troubleshoot: Activity,
  recommend: ThumbsUp,
  calendar_month: Calendar,
  group_add: UserPlus,
  sync_saved_locally: CheckCircle2,
  handshake: Handshake,
  trophy: Trophy,
  photo_camera: Camera,
  arrow_drop_down: ChevronDown,
  folder_open: FolderOpen,
  privacy_tip: ShieldCheck,
  volume_up: Volume2,
  subtitles: Captions,
  fullscreen: Maximize,
  pause: Pause,
  apps: AppsIcon,
  help_center: HelpCircle,
  person_add: UserPlus,
  task: ClipboardCheck,
  unpublished: EyeOff,
  image: ImageIcon,
  drag_indicator: GripVertical,
  filter_list: ListFilter,
  donut_large: PieChart,
  chevron_left: ChevronLeft,
  calendar_today: Calendar,
  format_quote: Quote,
  filter_alt_off: FilterX,
  bar_chart: BarChart3,
  content_copy: Copy,
  trending_down: TrendingDown,
  library_add: FilePlus2,
  send: Send,
  assignment_add: FilePlus2,
  save: Save,
  bug_report: Bug,
  download_for_offline: DownloadCloud,
};

interface IconProps {
  name: string;
  className?: string;
  /** pixel size; if omitted the icon scales to 1em (inherits font-size) */
  size?: number;
  fill?: boolean;
  strokeWidth?: number;
}

/**
 * Inline-SVG icon (lucide) — replaces the Material Symbols web font so icons
 * render instantly and work fully offline. Colour follows `currentColor`
 * (so Tailwind text-[#...] classes still work); size follows font-size via 1em
 * unless an explicit `size` is given.
 */
export default function Icon({ name, className, size, fill, strokeWidth = 2 }: IconProps) {
  const Cmp = MAP[name] || Circle;
  return (
    <Cmp
      className={cn("inline-block shrink-0 align-middle", className)}
      style={size ? { width: size, height: size } : { width: "1em", height: "1em" }}
      strokeWidth={strokeWidth}
      {...(fill ? { fill: "currentColor" } : {})}
    />
  );
}
